name: fokusin
description: "Aplikasi manajemen tugas dan pomodoro"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.8.0+1
  firebase_auth: ^5.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  fpdart: ^1.1.1
  go_router: ^14.8.1
  google_sign_in: ^6.2.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
